name: Copy Files and Create Installer

on:
  push:
    branches:
      - main # Change this to your default branch if different
  # You can add more triggers like pull_request, release, etc., as needed.

jobs:
  build:
    runs-on: ubuntu-latest # Change to your desired runner OS if required.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy files to installation directory
      run: |
        mkdir -p $HOME/AppData/singles-sorter
        cp -R source_code/* $HOME/AppData/singles-sorter/

    - name: Create Windows installer script
      run: |
        echo @echo off > installer.bat
        echo echo Installing Singles Sorter... >> installer.bat
        echo mkdir "%AppData%\singles-sorter" >> installer.bat
        echo xcopy /s /e /i "%~dp0source_code" "%AppData%\singles-sorter" >> installer.bat
        echo echo Installation complete. >> installer.bat

    - name: Save changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add installer.bat
        git commit -m "Create Windows installer script"
        git push
