name: Create Installer

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Copy files to installation folder
        run: |
          mkdir -p $HOME/AppData/singles-sorter
          cp -r source_code/* $HOME/AppData/singles-sorter
          cp add_uninstall_list.reg $HOME/AppData/singles-sorter

      - name: Package installer
        run: |
          npm install -g electron-packager
          electron-packager $HOME/AppData/singles-sorter singles-sorter-installer --platform=win32 --arch=x64 --out=installer --overwrite

      - name: Upload installer artifact
        uses: actions/upload-artifact@v2
        with:
          name: singles-sorter-installer
          path: installer/singles-sorter-installer-win32-x64
