name: Create Zip File

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger the workflow

jobs:
  create_zip_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: cd folder
        run: |
          cd source_code/
        working-directory: ${{ github.workspace }}
        
        
      - name: Create Zip File
        run: |
           zip -r source_code/software_files.zip *
        working-directory: ${{ github.workspace }}

      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v2
        with:
          name: software_files.zip
          path: $working-directory/software_files.zip
