name: Create Zip File

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger the workflow

jobs:
  create_zip_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Zip File
        run: |
          cd $GITHUB_WORKSPACE/source_code
          zip -r software_files.zip * # This will create a zip file containing all files in the source_code folder

      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v2
        with:
          name: software_files # Replace with your desired artifact name
          path: $GITHUB_WORKSPACE/source_code/software_files.zip # Replace with the correct path to the zip file
