name: Build and Release CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller music_tag jibrish_to_hebrew

    - name: Build EXE
      run: |
        pyinstaller --onefile --add-data "src/core/app/singer-list.csv;app" --name "Singles-Sorter" --icon "src/core/assets/icon.ico" "src/core/singles_sorter_v3.py"

    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Rename output file
      run: |
        move dist\Singles-Sorter.exe dist\Singles-Sorter-cli-${{ steps.get_version.outputs.VERSION }}.exe

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: true
        prerelease: true
        files: ./dist/Singles-Sorter-cli-${{ steps.get_version.outputs.VERSION }}.exe