name: Publish Release

on:
  push:
    tags:
      - 'v*.*' # Trigger the workflow on tag creation with the format "vX.Y.Z"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Replace with the Python version you need

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile python-project/singles_sorter_func.py # Replace 'main.py' with the name of your main Python file

    - name: Set version number
      run: |
        echo "1.0" > version.txt # Update version.txt with your desired version

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/main.exe # Replace 'main.exe' with the correct path to your generated EXE file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
