name: Publish Release

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Replace with the Python version you need

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build EXE
      run: |
        # Get the version number from the tag (e.g., v1.0.0)
        VERSION=$(echo "${{ github.ref }}" | cut -d'/' -f3)
        # Remove the 'v' prefix from the version (e.g., 1.0.0)
        VERSION=$(echo "${VERSION}" | cut -c 2-)

        # Run PyInstaller with custom name and version
        pyinstaller --onefile --name "Singles-Sorter-${VERSION}" python-project/singles_sorter_func.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref }}

    - name: Set version number
      run: |
        # Get the version number from the tag (e.g., v1.0.0)
        VERSION=$(echo "${{ github.ref }}" | cut -d'/' -f3)
        # Remove the 'v' prefix from the version (e.g., 1.0.0)
        VERSION=$(echo "${VERSION}" | cut -c 2-)
        echo "${VERSION}" > version.txt # Update version.txt with your desired version

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "dist/Singles-Sorter-${{ env.VERSION }}.exe" # Use double quotes and access the VERSION variable correctly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
