name: Publish EXE

on:
  push:
    branches:
      - gui

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller music_tag jibrish_to_hebrew flet

    - name: Build EXE
      run: |
        flet pack -i gui-project/assets/icon.ico gui-project/main.py --product-name "Singles Sorter" --product-version "12.9.0" --file-description "Software that sorts your singles folders through advanced automation" --copyright "nh.local11@gmail.com"


    - name: Create Artifact Directory
      run: mkdir -p artifacts
      
    - name: Copy Output File to Artifact Directory
      run: copy dist\singles_sorter.exe artifacts\ 

    - name: Zip Artifact Directory
      run: |
        cd artifacts
        powershell -Command "Compress-Archive -Path * -DestinationPath Singles-Sorter.zip"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: singles-sorter
        path: artifacts/Singles-Sorter.zip
