name: Publish Release

on:
  push:
    tags:
      - 'v*.*' # Trigger the workflow on tag creation with the format "vX.Y.Z"

env:
  VERSION: ${{ github.ref }} # Use the GitHub ref directly as the version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Replace with the Python version you need

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build EXE
      run: |
        # Remove the 'v' prefix from the version (e.g., 1.0.0)
        export VERSION=$(echo "${VERSION}" | cut -c 2-)
        # Run PyInstaller with custom name and version
        pyinstaller --onefile --name "Singles-Sorter-${VERSION}.exe" python-project/singles_sorter_func.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ env.VERSION }} # Pass the version to the build step

    - name: Set version number
      run: |
        # Remove the 'v' prefix from the version (e.g., 1.0.0)
        export VERSION=$(echo "${VERSION}" | cut -c 2-)
        echo "${VERSION}" > version.txt # Update version.txt with your desired version

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: "/home/runner/work/Singles-Sorter/Singles-Sorter/dist/Singles-Sorter-${VERSION}.exe" # Use double quotes for variable expansion
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
