name: APK Build and Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.27.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-apk.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Flet Build APK
      run: |
        flutter config --no-analytics
        flet build apk -v --include-packages flet_permission_handler

    - name: Get Version and Set Release Metadata
      id: get_version
      shell: bash
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        FILENAME="Singles-Sorter-${VERSION}.apk"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "FILENAME=$FILENAME" >> $GITHUB_OUTPUT
        echo "RELEASE_TITLE=מסדר הסינגלים $VERSION" >> $GITHUB_OUTPUT

    - name: Rename APK File
      run: |
        mv build/apk/*.apk build/apk/${{ steps.get_version.outputs.FILENAME }}

    - name: Create Draft Release
      uses: softprops/action-gh-release@v2.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: ${{ steps.get_version.outputs.RELEASE_TITLE }}
        draft: true
        prerelease: true
        files: |
          build/apk/${{ steps.get_version.outputs.FILENAME }}