name: Run Gemini API Processing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process_songs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai

      - name: Run Python Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python machine-learn/scrape_data/level0/Gemini-synthetic/gemini_api_creating.py
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: song-variations-output
          path: song_variations_output.txt
