name: Train NER model

on:
  push:
    branches:
      - machine-learn
    paths:
      - 'machine-learn/scrape_data/**'  # An action will only be performed if a file in the machine-learn folder changes

jobs:
  train-ner-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install spacy==3.7.5 pandas

      - name: Set working directory
        run: cd machine-learn/
        working-directory: ${{ github.workspace }}

      - name: Run training script
        run: |
          python machine-learn/creating_model_git.py

      - name: Read model name from file
        id: model-name
        run: echo "MODEL_NAME=$(cat /home/runner/work/Singles-Sorter/Singles-Sorter/machine-learn/model_name.txt)" >> $GITHUB_OUTPUT

      - name: Debug model name
        run: echo "Model name is ${{ steps.model-name.outputs.MODEL_NAME }}"


      - name: Move prepared file to internal folder
        run: |
          mv ${{ steps.model-name.outputs.MODEL_NAME }} machine-learn/

      - name: Move iteration_data.json to model folder
        run: |
          mv /home/runner/work/Singles-Sorter/Singles-Sorter/machine-learn/iteration_data.json machine-learn/${{ steps.model-name.outputs.MODEL_NAME }}/

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add machine-learn/${{ steps.model-name.outputs.MODEL_NAME }}
          git commit -m "Update ${{ steps.model-name.outputs.MODEL_NAME }} including iteration_data.json" || echo "No changes to commit"
          git push