name: Build and Upload Artifact

on:
  push:
    branches:
      - machine-learn


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller music_tag jibrish_to_hebrew spacy

    - name: Build EXE
      run: |
        pyinstaller --onefile --add-data "src/core/app/singer-list.csv;app" --name "Singles-Sorter" --icon "src/core/assets/icon.ico" "src/core/singles_sorter_v5.py"

    - name: Rename output file
      shell: pwsh
      run: |
        Move-Item -Path "dist\Singles-Sorter.exe" -Destination "dist\singles-sorter-cli.exe"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: singles-sorter-cli
        path: ./dist/singles-sorter-cli.exe
